routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('/projects', 'ProjectController');
    Route::resource('/backlog', 'BacklogController');
});

resources/views/aside.blade.php
<div class="col-md-3">
<ul class="bg-primary nav flex-column">
  <li class="nav-item border">
    <a class="text-white nav-link" href="{{route('projects.index')}}">PROYECTOS</a>
  </li>
  <li class="nav-item border">
    <a class="text-white  nav-link" href="#">TABLERO</a>
  </li>
  <li class="nav-item border">
    <a class=" text-white nav-link" href="{{route('backlog.index')}}">BACKLOG</a>
  </li>
  <li class="nav-item border">
    <a class=" text-white  nav-link" href="#">SPRINTS</a>
  </li>
</ul>
</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @include('aside')
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('Ingresaste corrctamente!') }}
                    Bienvenido a ISY
                </div>
            </div>
        </div>
    </div>
</div>
@endsection