routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('/projects', 'ProjectController');
    Route::resource('/backlog', 'BacklogController');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;
class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects=Project::all();
        return view ('project.index',compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $edit= false;
        $project = new Project();
        return view ('project.create',compact('project','edit'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            ['name'=>'required',
            'product_owner'=>'required',
            'scrum_master'=>'required',
            'development_team'=>'required',
            ]
        );
        $project = new Project();
        $project->name=$request->name;
        $project->product_owner=$request->product_owner;
        $project->scrum_master=$request->scrum_master;
        $project->development_team=$request->development_team;
        $project->save();
        return redirect('projects');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit= true;
        $project =  Project::find($id);
        return view ('project.create',compact('project','edit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(
            ['name'=>'required',
            'product_owner'=>'required',
            'scrum_master'=>'required',
            'development_team'=>'required',
            ]
        );
        $project = Project::find($id);
        $project->name=$request->name;
        $project->product_owner=$request->product_owner;
        $project->scrum_master=$request->scrum_master;
        $project->development_team=$request->development_team;
        $project->save();
        return redirect('projects');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project=Project::find($id);
        $project->delete();
        return redirect('projects');
    }
}

resources/views/project/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @include('aside')
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Crear Proyecto') }} <a href="{{route('projects.index')}}" class="btn btn-sm btn-success float-right">Listado de proyectos</a></div>
                @if(!$edit)
                <form action="{{route('projects.store')}}" method="POST">
                    @else
                    <form action="{{route('projects.update',['project' => $project->id])}}" method="POST">
                        <input name="_method" type="hidden" value="PUT">
                        @endif
                        @csrf
                        <div class="card-body">


                            <div class="form-group">
                                <label for="">Nombre</label>
                                <input type="text" name="name" value="{{$project->name}}" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Product Owner</label>
                                <input type="text" name="product_owner" value="{{$project->product_owner}}" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Scrum Master</label>
                                <input type="text" name="scrum_master" value="{{$project->scrum_master}}" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Equipo de Desarrollo</label>
                                <input type="text" name="development_team" value="{{$project->development_team}}" class="form-control">
                            </div>


                        </div>
                        <div class="card-footer bg-white">
                            <button class="mx-2 float-right btn btn-sm btn-primary">Guardar</button>
                            <a href="{{route('home')}}" class="mx-2 float-right btn btn-sm btn-secondary">Cancelar</a>
                        </div>
                    </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/project/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @include('aside')
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Listado Proyectos') }} <a href="{{route('projects.create')}}" class="btn btn-sm btn-success float-right">Crear Proyecto</a></div>

                <div class="card-body">

                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                                <th>Proyecto</th>
                                <th>Product Owner</th>
                                <th>Scrum Master</th>
                                <th>Eliminar</th>
                                <th>Modificar</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($projects as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>{{$item->product_owner}}</td>
                                <td>{{$item->scrum_master}}</td>
                                <td>
                                    
                                    <form action="{{route('projects.destroy',['project'=>$item->id])}}" method="post">
                                        <input class="btn btn-sm btn-danger" type="submit" value="Delete" />
                                        <input type="hidden" name="_method" value="delete" />
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    </form>
                                </td>
                                <td><a href="{{route('projects.edit',['project'=>$item->id])}}" class="btn btn-sm btn-primary">Modificar</a></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>
                <div class="card-footer">
                    <a href="{{route('home')}}" class="float-right btn btn-sm btn-secondary">Atrás</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection