routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('/projects', 'ProjectController');
    Route::resource('/backlog', 'BacklogController');
});

app/Backlog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Backlog extends Model
{
    public function projects()
    {
        return $this->belongsTo(Project::class, 'project_id')
            ->select('id', 'name');
    }
}

app/Http/Controllers/BacklogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Backlog;
use App\Project;

class BacklogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $backlog = Backlog::with(['projects'])->get();
        return view('backlog.index', compact('backlog'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $edit = false;
        $projects = Project::all();
        $backlog = new Backlog();
        return view('backlog.create', compact('backlog', 'edit', 'projects'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'name'=>'required',
                'user_field'=>'required',
                'funcional_field'=>'required',
                'profit_field'=>'required',
                'description'=>'required',
                'acceptance_requirements'=>'required',
                'responsable'=>'required',
                'score'=>'required',
                'sprint'=>'required',
                'project_id'=>'required',
            ]
        );
        $backlog = new Backlog();     
        $backlog->name=$request->name;   
        $backlog->user_field=$request->user_field;
        $backlog->funcional_field=$request->funcional_field;
        $backlog->profit_field=$request->profit_field;
        $backlog->description=$request->description;
        $backlog->acceptance_requirements=$request->acceptance_requirements;
        $backlog->responsable=$request->responsable;
        $backlog->score=$request->score;
        $backlog->sprint=$request->sprint;
        $backlog->project_id=$request->project_id;
        $backlog->save();
        return redirect('backlog');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = true;
        $projects = Project::all();
        $backlog =  Backlog::find($id);
        return view('backlog.create', compact('backlog', 'edit', 'projects'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(
            [
                'name'=>'required',
                'user_field'=>'required',
                'funcional_field'=>'required',
                'profit_field'=>'required',
                'description'=>'required',
                'acceptance_requirements'=>'required',
                'responsable'=>'required',
                'score'=>'required',
                'sprint'=>'required',
                'project_id'=>'required',
            ]
        );
        $backlog=Backlog::find($id);
        $backlog->name=$request->name;
        $backlog->user_field=$request->user_field;
        $backlog->funcional_field=$request->funcional_field;
        $backlog->profit_field=$request->profit_field;
        $backlog->description=$request->description;
        $backlog->acceptance_requirements=$request->acceptance_requirements;
        $backlog->responsable=$request->responsable;
        $backlog->score=$request->score;
        $backlog->sprint=$request->sprint;
        $backlog->project_id=$request->project_id;
        $backlog->save();
        return redirect('backlog');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $backlog=Backlog::find($id);
        $backlog->delete();
        return redirect('backlog');
    }
}

resources/views/backlog/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @include('aside')
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Crear Historia de Usuario') }} <a href="{{route('backlog.index')}}" class="btn btn-sm btn-success float-right">Listado de Backlog</a></div>
                @if(!$edit)
                <form action="{{route('backlog.store')}}" method="POST">
                    @else
                    <form action="{{route('backlog.update',['backlog' => $backlog->id])}}" method="POST">
                        <input name="_method" type="hidden" value="PUT">
                        @endif
                        @csrf
                        <div class="card-body">

                            <div class="form-group">
                                <label for="">Proyecto</label>
                                <select name="project_id" id="" class="form-control">
                                    @foreach($projects as $row)
                                    <option @if($backlog->project_id==$row->id) selected @endif value="{{$row->id}}">{{$row->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="">Nombre</label>
                                <input type="text" name="name" value="{{$backlog->name}}" class="form-control">
                            </div>
                            <div class="form-group row">
                                <div class="col-md-4">
                                    <label for="">Campo de usuario</label>
                                    <input type="text" name="user_field" value="{{$backlog->user_field}}" class="form-control">
                                </div>
                                <div class="col-md-4">
                                    <label for="">Campo de funcionalidad</label>
                                    <input type="text" name="funcional_field" value="{{$backlog->funcional_field}}" class="form-control">
                                </div>
                                <div class="col-md-4">
                                    <label for="">Campo de beneficio</label>
                                    <input type="text" name="profit_field" value="{{$backlog->profit_field}}" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">Descripción</label>
                                <input type="text" name="description" value="{{$backlog->description}}" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Criterios de aceptación</label>
                                <input type="text" name="acceptance_requirements" value="{{$backlog->acceptance_requirements}}" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Responsable</label>
                                <input type="text" name="responsable" value="{{$backlog->responsable}}" class="form-control">
                            </div>
                            <div class="form-group row">
                                <div class="col-md-6">
                                    <label for="">Puntuación</label>
                                    <input type="text" name="score" value="{{$backlog->score}}" class="form-control ">
                                </div>
                                <div class="col-md-6">
                                    <label for="">Sprint</label>
                                    <input type="number" name="sprint" value="{{$backlog->sprint}}" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="card-footer bg-white">
                            <button class="mx-2 float-right btn btn-sm btn-primary">Guardar</button>
                            <a href="{{route('backlog.index')}}" class="mx-2 float-right btn btn-sm btn-secondary">Cancelar</a>
                        </div>
                    </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/backlog/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @include('aside')
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Listado Backlog') }} <a href="{{route('backlog.create')}}" class="btn btn-sm btn-success float-right">Crear Historia de Usuario</a></div>

                <div class="card-body">

                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                                <th>Proyecto</th>
                                <th>Nombre</th>
                                <th>Sprint</th>
                                <th>Eliminar</th>
                                <th>Modificar</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($backlog as $item)
                            <tr>
                                <td>{{$item->projects->name}}</td>
                                <td>{{$item->name}}</td>
                                <td>{{$item->sprint}}</td>
                                <td>
                                    
                                    <form action="{{route('backlog.destroy',['backlog'=>$item->id])}}" method="post">
                                        <input class="btn btn-sm btn-danger" type="submit" value="Delete" />
                                        <input type="hidden" name="_method" value="delete" />
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    </form>
                                </td>
                                <td><a href="{{route('backlog.edit',['backlog'=>$item->id])}}" class="btn btn-sm btn-primary">Modificar</a></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>
                <div class="card-footer">
                    <a href="{{route('home')}}" class="float-right btn btn-sm btn-secondary">Atrás</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection